=== TomasTS14/LMS/supermercado/supermercado.dtd
<!ELEMENT supermercado (trabajador*,producto*,horario)>
<!ELEMENT trabajador (dni,nombre,(email|telefono))>
<!ELEMENT producto (codigo,nombre,categoria?)>
<!ELEMENT horario (#PCDATA)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>

=== TomasTS14/LMS/supermercado/datos.xml
<!DOCTYPE supermercado SYSTEM "supermercado.dtd">
<supermercado>
    <trabajador>
        <dni>127398127983</dni>

        <nombre>Matias</nombre>
        <email>matiaschiquito@hotmail.com</email>

    </trabajador>
    <producto>

        <codigo>123123</codigo>
        <nombre>pasta fea</nombre>
        <categoria>pasta de las feas</categoria>
    </producto>

    <horario>
        L-V 9:00-20:00
    </horario>
</supermercado>
