=== TomasTS14/LMS/XSD_2/files.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="files">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="dir" />
            </xs:sequence>
        </xs:complexType>

    </xs:element>
    <xs:complexType name="directorio">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="dir" minOccurs="0" maxOccurs="unbounded" />
            <xs:element ref="file" minOccurs="0" maxOccurs="unbounded" />
        </xs:choice>
        <xs:attribute name="path" type="xs:string" />
    </xs:complexType>
    <xs:complexType name="file">
        <xs:sequence>
            <xs:element name="content" minOccurs="0"></xs:element>
            <xs:element name="permission" minOccurs="0"></xs:element>
        </xs:sequence>
        <xs:attribute name="name" />
        <xs:attribute name="references" />
    </xs:complexType>
    <xs:element name="dir" type="directorio"></xs:element>
    <xs:element name="file" type="file"></xs:element>
</xs:schema>

=== TomasTS14/LMS/XSD_2/files.xml
<files xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="files.xsd">
    <dir path="/">
        <dir path="home">
            <dir path="sergio">
                <dir path="Downloads">
                    <file name="examenes.txt">
                        <content>LMSGI, BD, DWES</content>
                        <permission>755</permission>
                    </file>
                </dir>
                <dir path="Documents">
                    <file name="notas.txt">
                        <content>Este es mi fichero de notas personales</content>
                        <permission>700</permission>
                    </file>
                </dir>
                <file name="accesoDirecto" references="/home/sergio/Downloads/examenes.txt" />
            </dir>
        </dir>
    </dir>
</files>
