=== TomasTS14/LMS/XSD_1/tienda.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tienda">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="cliente" minOccurs="0" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="cliente">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="compra" minOccurs="0" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
            <xs:attribute name="codigo"></xs:attribute>
            <xs:attribute name="email"></xs:attribute>
            <xs:attribute name="nombre"></xs:attribute>
            <xs:attribute name="telefono"></xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="compra">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="producto" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
            <xs:attribute name="codigo"></xs:attribute>
            <xs:attribute name="importe"></xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="producto">
        <xs:complexType>
            <xs:attribute name="codigo"></xs:attribute>
            <xs:attribute name="nombre"></xs:attribute>
            <xs:attribute name="precio"></xs:attribute>
            <xs:attribute name="proveedor"></xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== TomasTS14/LMS/XSD_1/tienda.xml
<tienda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tienda.xsd">
    <cliente codigo="1" email="a@a.a" nombre="Ana" telefono="666555444">
        <compra codigo="1" importe="40€">
            <producto codigo="1" nombre="FIFA 20" precio="40€" proveedor="EA"></producto>
        </compra>
    </cliente>
    <cliente codigo="2" email="b@b.b" nombre="Belén">
        <compra codigo="2" importe="55€">
            <producto codigo="2" nombre="GTA V" precio="30€"></producto>
            <producto codigo="3" nombre="FarCry V" precio="25€" proveedor="Ubisoft"></producto>
        </compra>
    </cliente>
    <cliente codigo="3" email="c@c.c" nombre="Cristina" telefono="666333444" />
</tienda>
